Repository guoshiqiufeng/dify-spring-boot-starter, pull requests merged in 2025-08, with the labels that each got.

#185 fix: agent_thought return
  dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/ChatMessageSendCompletionResponse.java
  gradle.properties
Labels: size:S

#187 feat: DifyDatasetBuilder expand apikey
  dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/builder/DifyDatasetBuilder.java
  dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/builder/DifyDatasetBuilderTest.java
  dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/builder/DifyDatasetBuilder.java
  dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/builder/DifyDatasetBuilderTest.java
  docs/en/guide/builder.md
  docs/guide/builder.md
Labels: size:L

#188 feat: Dataset support Update Document Status
  dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/dataset/DifyDatasetDefaultClient.java
  dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/dataset/DifyDatasetDefaultClient.java
  dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/DifyDataset.java
  dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/client/DifyDatasetClient.java
  dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/constant/DatasetUriConstant.java
  dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/response/DatasetStatusResponse.java
  dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/enums/document/DocActionEnum.java
  dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/impl/DifyDatasetClientImpl.java
  dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/impl/DifyDatasetClientImplTest.java
Labels: size:L

#189 feat: change document status
  dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/builder/DifyDatasetBuilder.java
  dify/dify-client/dify-client-spring5/src/main/java/io/github/guoshiqiufeng/dify/client/spring5/dataset/DifyDatasetDefaultClient.java
  dify/dify-client/dify-client-spring5/src/test/java/io/github/guoshiqiufeng/dify/client/spring5/dataset/DifyDatasetDefaultClientTest.java
  dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/builder/DifyDatasetBuilder.java
  dify/dify-client/dify-client-spring6/src/main/java/io/github/guoshiqiufeng/dify/client/spring6/dataset/DifyDatasetDefaultClient.java
  dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/builder/DifyDatasetBuilderTest.java
  dify/dify-client/dify-client-spring6/src/test/java/io/github/guoshiqiufeng/dify/client/spring6/dataset/DifyDatasetDefaultClientTest.java
  dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/DifyDataset.java
  dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/client/DifyDatasetClient.java
  dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/dto/response/DatasetStatusResponse.java
  dify/dify-support/dify-support-dataset/src/main/java/io/github/guoshiqiufeng/dify/dataset/impl/DifyDatasetClientImpl.java
  dify/dify-support/dify-support-dataset/src/test/java/io/github/guoshiqiufeng/dify/dataset/impl/DifyDatasetClientImplTest.java
  dify/spring-boot-starter/dify-spring-boot-starter/src/test/java/io/github/guoshiqiufeng/dify/boot/DatasetTest.java
  dify/spring-boot2-starter/dify-spring-boot2-starter/src/test/java/io/github/guoshiqiufeng/dify/boot/DatasetTest.java
  docs/en/guide/feature/chat.md
  docs/en/guide/feature/dataset.md
  docs/guide/builder.md
  docs/guide/feature/chat.md
  docs/guide/feature/dataset.md
Labels: size:XL

#191 expand event: error、ping
  dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/ChatMessageSendCompletionResponse.java
  dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/dto/response/jackson/ChatMessageSendCompletionResponseDeserializer.java
  dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/enums/StreamEventEnum.java
  dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/dto/response/jackson/ChatMessageSendCompletionResponseDeserializerTest.java
  dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/enums/StreamEventEnumTest.java
Labels: size:L

#192 dependency: update springboot3 to 3.5.5
  ext.gradle
Labels: size:XS

#194 feat: chat message event
  dify/dify-core/src/main/java/io/github/guoshiqiufeng/dify/core/pipeline/PipelineContext.java
  dify/dify-core/src/main/java/io/github/guoshiqiufeng/dify/core/pipeline/PipelineHandler.java
  dify/dify-core/src/main/java/io/github/guoshiqiufeng/dify/core/pipeline/PipelineModel.java
  dify/dify-core/src/main/java/io/github/guoshiqiufeng/dify/core/pipeline/PipelineProcess.java
  dify/dify-core/src/main/java/io/github/guoshiqiufeng/dify/core/pipeline/PipelineTemplate.java
  dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/pipeline/PipelineContextTest.java
  dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/pipeline/PipelineHandlerTest.java
  dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/pipeline/PipelineModelTest.java
  dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/pipeline/PipelineProcessTest.java
  dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/pipeline/PipelineTemplateTest.java
  dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/pipeline/TestPipelineModel.java
  dify/dify-core/src/test/java/io/github/guoshiqiufeng/dify/core/pipeline/TestPipelineProcess.java
  dify/dify-support/dify-support-chat/build.gradle
  dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/impl/DifyChatClientImpl.java
  dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/pipeline/ChatMessagePipelineModel.java
  dify/dify-support/dify-support-chat/src/main/java/io/github/guoshiqiufeng/dify/chat/pipeline/DifyChatPipelineUtils.java
  dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/pipeline/ChatMessagePipelineModelTest.java
  dify/dify-support/dify-support-chat/src/test/java/io/github/guoshiqiufeng/dify/chat/pipeline/DifyChatPipelineUtilsTest.java
  dify/dify-support/dify-support-workflow/src/main/java/io/github/guoshiqiufeng/dify/workflow/dto/response/stream/EmptyData.java
  dify/spring-boot-starter/dify-spring-boot-starter-autoconfigure/src/main/java/io/github/guoshiqiufeng/dify/springboot/autoconfigure/DifyChatAutoConfiguration.java
  dify/spring-boot2-starter/dify-spring-boot2-starter-autoconfigure/src/main/java/io/github/guoshiqiufeng/dify/springboot2/autoconfigure/DifyChatAutoConfiguration.java
  docs/en/guide/event/chat.md
  docs/en/guide/event/introduction.md
  docs/en/guide/feature/dataset.md
  docs/guide/event/chat.md
  docs/guide/event/introduction.md
  docs/guide/feature/dataset.md
  ext.gradle
Labels: size:XXL
